services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
      POSTGRES_DB=vistasql
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: your_jwt_secret_key
      ENVIRONMENT: dev
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src

volumes:
  db_data: